fix(engine): add ReadError to 'connectivity_issue_retry'
Mergifyio/mergify-engine pull request #1352
Opened 2020-08-28 13:38 UTC by GuillaumeOj

Fix for MERGIFY-ENGINE-1RT

2020-08-28 13:42 UTC, sileht commented
I think `ReadError` inherit from `RequestError`

2020-08-31 17:28 UTC, GuillaumeOj commented
I have changed the PR title since its not really a fix but just a test improvement

2020-09-01 07:50 UTC, jd requested changes
Great!

For Sentry you can use:
`Fixes MERGIFY-ENGINE-1RT` in your commit so it triggers the close on Sentry side.

2020-09-02 05:01 UTC, sileht approved these changes

2020-09-02 05:01 UTC, merged