feat: add +1 reaction when user post comment to mergify
Mergifyio/mergify-engine pull request #1440
Opened 2020-09-30 18:09 UTC by sileht

Related: MRGFY-70

2020-09-30 18:20 UTC, jd submitted a review, later dismissed

2020-09-30 18:20 UTC, jd commented on mergify_engine/engine/commands_runner.py
> +                        "Accept": "application/vnd.github.squirrel-girl-preview+json"
Why not using `api_version`?

2020-09-30 19:11 UTC, jd requested changes
same comment

2020-09-30 20:26 UTC, sileht commented on mergify_engine/engine/commands_runner.py
> +                        "Accept": "application/vnd.github.squirrel-girl-preview+json"
fixed

2020-10-01 08:35 UTC, jd approved these changes

2020-10-01 08:44 UTC, merged