feat: post summary as soon as possible for new PR
Mergifyio/mergify-engine pull request #1493
Opened 2020-10-08 19:44 UTC by sileht

2020-10-08 21:03 UTC, jd requested changes

2020-10-08 21:03 UTC, jd commented on mergify_engine/worker.py
> +# -*- encoding: utf-8 -
:(

2020-10-14 11:33 UTC, sileht commented on mergify_engine/context.py
> +        installation_id = client.auth.installation["id"]
it's not a new thing here, I just move the code. In Github action mode id is just 0

2020-10-14 14:01 UTC, jd approved these changes

2020-10-15 11:42 UTC, merged