feat(actions): limit rebase action to repo less than 512mo
Mergifyio/mergify-engine pull request #1871
Opened 2021-01-21 14:54 UTC by CamClrt

Fixes MRGFY-216

2021-01-21 15:46 UTC, jd submitted a review, later dismissed

2021-01-21 15:46 UTC, jd commented on mergify_engine/actions/rebase.py
> +                    "",
```suggestion
                    "Branch rebase failed"
                    "Your repository is above {} KB.\n{}".format(config.NOSUB_MAX_REPO_SIZE_KB, ctxt.subscription.missing_feature_reason(ctxt.pull["base"]["repo"]["owner"]["login"]),
```

2021-01-22 07:29 UTC, jd requested changes

2021-01-22 07:29 UTC, jd commented on mergify_engine/actions/rebase.py
> +                    "Branch rebase failed: repository too big and no subscription active",
```suggestion
                    "Branch rebase failed",
```

2021-01-22 08:44 UTC, CamClrt commented on mergify_engine/actions/rebase.py
> +                    "Branch rebase failed: repository too big and no subscription active",
Oups !

2021-01-22 08:55 UTC, jd approved these changes

2021-01-22 08:56 UTC, jd submitted a review, later dismissed
we need to update the doc too

2021-01-22 11:16 UTC, jd requested changes
This is also true for the `rebase` command.

2021-01-22 13:33 UTC, jd approved these changes

2021-01-22 13:40 UTC, merged