update queue api
Mergifyio/mergify-engine pull request #1963
Opened 2021-02-01 15:01 UTC by CamClrt

2021-02-02 14:12 UTC, jd requested changes

2021-02-02 14:12 UTC, jd commented on mergify_engine/tests/unit/test_clients.py
> +        ).respond_with_json({"work": True}, status=200)
It looks like this is really identical to the previous test. Could you refactor this so we follow [DRY](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself)? 😄

2021-02-02 14:19 UTC, sileht commented
In `_set_installation()` we actually set `self.owner_id`, can we also set `self.owner` ? so once the authentication is done, we always have both sets, whatever the one we use initially.

2021-02-02 14:20 UTC, sileht commented on mergify_engine/tests/unit/test_clients.py
> +            assert ret.json()["work"]
Can you also check that client.auth.owner and client.auth.owner_id have the expected value (and you can also add it the previous test).

2021-02-03 10:43 UTC, sileht commented on mergify_engine/tests/unit/test_clients.py
> +def _httpserver_connect(httpserver: httpserver.HTTPServer, endpoint: str) -> None:
You can go even further by also passing the HTTP client `auth=` to this method, so when the `with AsyncGithubInstallationClient..` and all assert can be moved in this method.

2021-02-03 17:14 UTC, jd approved these changes

2021-02-03 17:14 UTC, jd requested changes
just one thing: can you squash your commits?

2021-02-04 09:08 UTC, CamClrt commented
> just one thing: can you squash your commits?

Ok, I will do it in one commit. Before, I will also add a functional test.

2021-02-05 07:32 UTC, sileht commented on mergify_engine/tests/unit/test_clients.py
> +            github.get_auth(owner_id=github_types.GitHubAccountIdType(12345))
```
            _httpserver_connect(
                httpserver, "/user/12345/installation", github.get_auth(owner_id=github_types.GitHubAccountIdType(12345))
            )
```

2021-02-05 07:33 UTC, sileht commented on mergify_engine/tests/unit/test_clients.py
> +    with mock.patch(
This can goes in _httpserver_connect

2021-02-05 07:33 UTC, sileht commented on mergify_engine/tests/unit/test_clients.py
> +            _httpserver_connect(
`async def` function have to be awaited to be executed. (eg: `await _httpserver_connect(...)`)

2021-02-05 07:34 UTC, sileht commented on mergify_engine/tests/unit/test_clients.py
> +gh_fake_response = {
The response can goes in `_httpserver_connect`, it's used anywhere else.

2021-02-05 07:37 UTC, sileht commented on mergify_engine/tests/unit/test_clients.py
> +async def _httpserver_connect(
The name is too generic,  something like `_do_test_client_installation_token()`.

2021-02-05 13:53 UTC, jd commented on mergify_engine/tests/functional/test_github_async_client.py
> +        client = github.aget_client(self.o_integration.login, self.o_integration.id)
since both login and ids are passed, I guess only one is used?
do we want to test only `id` being passed there?

2021-02-05 13:54 UTC, jd reviewed
for the commit you should use `refactor`, not `chore` I'd say.

2021-02-08 15:01 UTC, jd reviewed
LGTM I'll let @sileht validates

2021-02-08 15:18 UTC, sileht approved these changes

2021-02-08 15:18 UTC, merged