Pull request for installer
Mergifyio/mergify-engine pull request #2056
Opened 2021-02-15 18:43 UTC by sileht

## feat: add docker configuration

Initial step to be able to deploy the engine as docker image

Fixes MRGFY-12

## feat: allow to have only one redis

## feat: adapt docker image for heroku

## feat: introduce installer

2021-02-15 19:24 UTC, jd requested changes
Is there a good reason to have this installer in this repo?

2021-02-15 19:24 UTC, jd commented on .gitignore
> +.mypy_cache
Split in another PR

2021-02-15 19:24 UTC, jd commented on .gitignore
> +yarn-error.log*
Those last 3 should be in a different PR too

2021-02-15 19:24 UTC, jd commented on installer/asgi.py
> +)
Should this be placed in a installer directory so it's clear it's not the engine itself?

2021-02-23 09:02 UTC, jd reviewed
Do we need dependabot set up for this directory?

2021-02-26 10:17 UTC, sileht commented
> Do we need dependabot set up for this directory?

yes

2021-02-26 13:32 UTC, jd approved these changes

2021-02-26 13:37 UTC, merged