feat(queue): add support strict_method
Mergifyio/mergify-engine pull request #2218
Opened 2021-03-16 16:52 UTC by sileht

When the first PR in queue is rebased, we can now select the method to
use.

2021-03-16 16:56 UTC, sileht commented
Not sure we should call it strict_method here. Also this option may be confusing since we use it only for the first PR in train and not for the temporary merge-queue pull request.

2021-03-16 17:00 UTC, sileht commented
Depends-On: https://github.com/Mergifyio/mergify-engine/pull/2219

2021-03-16 17:08 UTC, jd requested changes

2021-03-16 17:08 UTC, jd commented on mergify_engine/actions/queue.py
>          voluptuous.Required("commit_message", default="default"): voluptuous.Any(
doc update?

2021-03-16 17:26 UTC, sileht commented
Do we keep `strict_method` ? Or do I rename it `update_method` ?

2021-03-17 08:32 UTC, jd commented
Sorry, I missed your comment in the first place. You're right I don't think `strict` means anything in that context.

My question would be, why does it apply only to the first PR? I imagine that if you set it to `rebase` you could build the merge cars by rebasing PR on top of each others?

2021-03-17 21:53 UTC, closed without merging