refactor MRGFY 346
Mergifyio/mergify-engine pull request #2268
Opened 2021-03-23 14:00 UTC by CamClrt

2021-03-23 14:36 UTC, CamClrt commented
To be validated, it's necessary to check and merge this [PR](https://github.com/Mergifyio/mergify.io/pull/2044) before

2021-03-24 09:12 UTC, sileht submitted a review, later dismissed
Looks good, but you need to rebase it, The new `train` queues mechanism have been merged yesterday and it changes some stuffs there.

2021-03-24 17:51 UTC, sileht requested changes

2021-03-24 17:51 UTC, sileht commented on mergify_engine/tests/functional/test_engine.py
> -        # with the older endpoint
We should keep that and just change the returned payload

2021-03-24 17:51 UTC, sileht commented on mergify_engine/tests/functional/test_engine.py
> -        # with the older endpoint
You can also  complete the test in test_queue.py that query this API

2021-03-24 17:51 UTC, sileht commented on mergify_engine/web/root.py
> -        async with github.aget_client(owner_id=owner_id) as client:
Both endpoints must be exactly the same. And we should not duplicate the code.

2021-03-25 14:37 UTC, sileht approved these changes

2021-03-25 14:42 UTC, merged