copy fix and command
Mergifyio/mergify-engine pull request #2380
Opened 2021-04-08 16:35 UTC by sileht

## fix(copy): delete temporary branches

copy branches starts by mergify/copy. We only clean mergify/bp branches.

This change also cleanup copy branches

Fixes MRGFY-385

## feat: allow copy command

Fixes MRGFY-384

2021-04-08 17:13 UTC, sileht commented
I have already set `MERGIFYENGINE_BOT_USER_LOGIN` in heroku

2021-04-09 07:10 UTC, jd requested changes

2021-04-09 07:10 UTC, jd commented on mergify_engine/data/default_pull_request_rules.yml
> +
if the file is empty we could probably just remove it

2021-04-09 13:34 UTC, jd approved these changes

2021-04-09 13:47 UTC, sileht commented
@mergifyio update

2021-04-09 14:03 UTC, sileht commented
@Mergifyio update

2021-04-09 15:06 UTC, merged