fix: allow to set default for queue name
Mergifyio/mergify-engine pull request #2381
Opened 2021-04-08 17:16 UTC by sileht

This makes defaults working with `Required` config key, like the queue
name.

2021-04-08 17:16 UTC, sileht commented
Depends on https://github.com/Mergifyio/mergify-engine/pull/2380

2021-04-09 07:05 UTC, jd requested changes

2021-04-09 07:05 UTC, jd commented on docs/source/commands.rst
> +copy
That does not sound related to the PR?

2021-04-09 16:22 UTC, jd submitted a review, later dismissed

2021-04-09 16:22 UTC, jd commented on mergify_engine/rules/__init__.py
> +<<<<<<< HEAD
lol

2021-04-12 17:15 UTC, jd approved these changes

2021-04-12 17:20 UTC, merged