feat: report team resolution errors
Mergifyio/mergify-engine pull request #2424
Opened 2021-04-15 18:31 UTC by sileht

This introduces a new mechanism to track conditions that may raise error
during its evaluation.

This change a bit the behavior of the engine. Before team resolution was
just ignored, and the rule can never ever match. Now we will report the
issue in the Summary.

2021-04-15 18:36 UTC, sileht commented
![image](https://user-images.githubusercontent.com/200878/114920862-2e727480-9e2a-11eb-8785-2afd73385fd9.png)

2021-04-15 18:59 UTC, jd requested changes
Awesome work!

2021-04-15 18:59 UTC, jd commented on mergify_engine/rules/live_resolvers.py
> +        values = [values]
out of the scope of this PR but this really should go away

2021-04-15 18:59 UTC, jd commented on mergify_engine/tests/functional/test_engine.py
> +            "Team `@mergifyio-testing/noexists` does not exists",
```suggestion
            "Team `@mergifyio-testing/noexists` does not exist",
```

2021-04-15 18:59 UTC, jd commented on mergify_engine/tests/functional/test_engine.py
> +            "Team `@another-org/testing` is not part of the organization",
Maybe say which organization if you can?

2021-04-16 15:03 UTC, jd approved these changes

2021-04-16 15:08 UTC, merged