Pull request for bot_account_backport2
Mergifyio/mergify-engine pull request #2482
Opened 2021-04-27 14:25 UTC by sileht

## refactor(bot_account): do bot_account check the same everywhere

This creates an helper function to validate the bot_account

## feat(copy/backport): add bot_account option

2021-04-28 12:28 UTC, jd submitted a review, later dismissed
doc?

2021-04-29 13:02 UTC, jd requested changes

2021-04-29 13:02 UTC, jd commented on docs/source/actions/backport.rst
> +       itself.
```suggestion
       If no ``bot_account`` is set, Mergify backports the pull request
       itself.
```

2021-04-29 13:02 UTC, jd commented on docs/source/actions/copy.rst
> +       If no ``bot_account`` is set, Mergify will copy the pull request
```suggestion
       If no ``bot_account`` is set, Mergify copies the pull request
```

2021-04-29 13:02 UTC, jd commented on mergify_engine/duplicate_pull.py
> +            )
Do we miss the plan feature check?

2021-04-29 14:36 UTC, sileht commented on mergify_engine/duplicate_pull.py
> +            )
This is done in the action.

2021-04-29 15:14 UTC, jd approved these changes

2021-04-29 15:14 UTC, merged