feat(conditions): add calendar condition
Mergifyio/mergify-engine pull request #2709
Opened 2021-06-01 09:48 UTC by sileht

Change-Id: Ia58ae9db00a50997954346435314b7231363f158

Depends-On: #2708

2021-06-01 09:48 UTC, sileht commented
This pull request is part of a stack:
1. feat(rules): allow and/or in conditions ([#2691](https://github.com/Mergifyio/mergify-engine/pull/2691))
1. feat: allow merged/closed/author/base/head in and/or conditions ([#2692](https://github.com/Mergifyio/mergify-engine/pull/2692))
1. feat(conditions): allow checks condition in and/or ([#2693](https://github.com/Mergifyio/mergify-engine/pull/2693))
1. refactor(filter): make it generic ([#2694](https://github.com/Mergifyio/mergify-engine/pull/2694))
1. feat(time): add time conditions ([#2695](https://github.com/Mergifyio/mergify-engine/pull/2695))
1. feat(conditions): add day/month/year/day-of-week conditions ([#2705](https://github.com/Mergifyio/mergify-engine/pull/2705))
1. feat(conditions): add support for named day-of-week ([#2708](https://github.com/Mergifyio/mergify-engine/pull/2708))
1. feat(conditions): add calendar condition ([#2709](https://github.com/Mergifyio/mergify-engine/pull/2709))

2021-06-15 13:39 UTC, jd requested changes

2021-06-15 13:39 UTC, jd commented on docs/source/conditions.rst
> +   ``calendar`` only support ``=`` and ``!=``
```suggestion
   ``current-time`` does not support ``~=``, ``=`` and ``!=`` operators.
   ``schedule`` only supports ``=`` and ``!=``.
```

2021-06-15 13:39 UTC, jd commented on docs/source/conditions.rst
> +     - A calendar, e.g.: ``Mon-Fri``, ``12:00-18:00`` or ``Mon-Fri 12:00-18:00``
```suggestion
   * - ``schedule``
     - string
     - A calendar schedule, e.g., ``Mon-Fri``, ``12:00-18:00`` or ``Mon-Fri 12:00-18:00``.
```

2021-06-15 13:39 UTC, jd commented on mergify_engine/rules/filter.py
> +        "@": typing.Any,
- typing?
- add a comment about what this operator does

2021-06-15 14:09 UTC, jd approved these changes

2021-06-15 14:09 UTC, jd commented on docs/source/conditions.rst
> +     - A schedule, e.g., ``Mon-Fri``, ``12:00-18:00`` or ``Mon-Fri 12:00-18:00``
```suggestion
     - A schedule, e.g., ``Mon-Fri``, ``12:00-18:00`` or ``Mon-Fri 12:00-18:00``.
```

2021-06-15 14:11 UTC, merged