chore(deps): bump python-dotenv from 0.18.0 to 0.19.0
Mergifyio/mergify-engine pull request #2969
Opened 2021-07-31 16:06 UTC by ErwanSimonetti

Bumps [python-dotenv](https://github.com/theskumar/python-dotenv) from 0.18.0 to 0.19.0.
- [Release notes](https://github.com/theskumar/python-dotenv/releases)
- [Changelog](https://github.com/theskumar/python-dotenv/blob/master/CHANGELOG.md)
- [Commits](https://github.com/theskumar/python-dotenv/compare/v0.18.0...v0.19.0)

---
updated-dependencies:
- dependency-name: python-dotenv
  dependency-type: direct:production
  update-type: version-update:semver-minor
...

Signed-off-by: dependabot[bot] <support@github.com>

## Description of the change

> Description here

## Related issues

> Fix #xyz

## Checklists

### Development

- [X] All checks must pass (Semantic Pull Request, pep8, requirements, unit tests, functional tests, security checks, …)
- [X] The code changed/added as part of this pull request must be covered with tests
- [X] Hotfixes must have a link to Sentry issue and the ``hotfix`` label
- [X] Features must have a link to a Linear task

### Code Review

Code review policies are handled and automated by Mergify.

* When all tests pass, reviewers will be assigned automatically.
* When change is approved by at least one review and no pending review are
  remaining, pull request is retested against its base branch.
* The pull request is then merged automatically.

2021-08-02 08:05 UTC, jd requested changes
The body of your pull request contains a boilerplate. That should not be the case. You should also refer #2951 with a `Fixes`, probably.

2021-08-02 08:05 UTC, jd commented on mergify_engine/config.py
> +dotenv.load_dotenv(dotenv_path=dotenv_path, override=True)
You cannot break what is existing, i.e., loading the file from the env variable.

2021-08-12 08:55 UTC, ErwanSimonetti commented on mergify_engine/config.py
> +    raise ValueError("Getenv test settings should not be None")
Because `os.path.abspath` cannot have an `Optional[str]` as argument (which `getenv_test_settings` could be if we didn't check)

2021-08-12 08:59 UTC, jd commented on mergify_engine/config.py
> +    raise ValueError("Getenv test settings should not be None")
Then don't call `os.path.abspath` if the result is `None`? 😉

2021-08-12 09:03 UTC, ErwanSimonetti commented on mergify_engine/config.py
> +    raise ValueError("Getenv test settings should not be None")
Isn't that what I already did ?

2021-08-12 09:04 UTC, jd commented on mergify_engine/config.py
> +    raise ValueError("Getenv test settings should not be None")
You do that indeed but you don't do *only* that. You also raise an error. This was not the case before.

2021-08-12 09:09 UTC, ErwanSimonetti commented on mergify_engine/config.py
> +getenv_test_settings = os.getenv("MERGIFYENGINE_TEST_SETTINGS")
Which line shouldn't I change ? L235 ?

2021-08-12 09:15 UTC, jd commented on mergify_engine/config.py
> +getenv_test_settings = os.getenv("MERGIFYENGINE_TEST_SETTINGS")
234

2021-08-12 09:36 UTC, jd commented on mergify_engine/config.py
> +getenv_test_settings = os.getenv("MERGIFYENGINE_TEST_SETTINGS")
It's fine using a variable. Why are you changing the name of it?

2021-08-12 09:42 UTC, ErwanSimonetti commented on mergify_engine/config.py
> +getenv_test_settings = os.getenv("MERGIFYENGINE_TEST_SETTINGS")
Oh I see my mistake sorry

2021-08-12 11:24 UTC, closed without merging