feat(queues): allow to batch pull requests
Mergifyio/mergify-engine pull request #3012
Opened 2021-08-13 10:19 UTC by sileht

Change-Id: I82c3c6082d435dabdbbfbbb47ea5b43cb020683f

2021-08-13 15:17 UTC, jd submitted a review, later dismissed

2021-08-13 15:17 UTC, jd commented on mergify_engine/queue/merge_train.py
> +                        headline = "🕵️  This combination of pull requests has failed check. Mergify is waiting for other pull requests ahead in the queue to understand which one is responsible for th
```suggestion
                        headline = "🕵️  This combination of pull requests has failed checks. Mergify is waiting for other pull requests ahead in the queue to understand which one is responsible for the failure. 🕵️"
```

2021-08-13 15:17 UTC, jd commented on releasenotes/notes/queue-batch-0e6eb62939368608.yaml
> +    row without checking them individualy
```suggestion
    Add ``batch_size`` option to queue rules. The new option allows to check
    multiple pull requests within each speculative check.
```

Don't duplicate the doc here… which is, you should put the rest of the text into the doc, not here.

2021-08-17 08:50 UTC, jd submitted a review, later dismissed

2021-08-17 08:50 UTC, jd commented on docs/source/actions/queue.rst
> +       between 1 and 20.
```suggestion
     - |premium plan tag| The maximum number of pull requests per speculative check in the queue. Must be
       between 1 and 20.
```

2021-08-17 08:50 UTC, jd commented on docs/source/actions/queue.rst
> +``2``, Mergify will create up to new 2 pull requests to check if the first
```suggestion
``2``, Mergify will create up to 2 new pull requests to check if the first
```

2021-08-17 08:50 UTC, jd commented on docs/source/actions/queue.rst
> +pull requests.
```suggestion
For example, by settings ``speculative_checks: 2`` and ``batch_size: 3``,
Mergify will create two pull requests: a first one to check if the first three enqueued pull requests are mergeable, and a second one to check the three next enqueued pull requests.
```

2021-08-17 08:50 UTC, jd commented on mergify_engine/queue/merge_train.py
> +                tmp_pull_title = f"The pull requests {refs} cannot be merged and have will be splitted"
```suggestion
                tmp_pull_title = f"The pull requests {refs} cannot be merged and will be split"
```

2021-08-17 08:50 UTC, jd commented on mergify_engine/queue/merge_train.py
> +                        headline = "🕵️  This combination of pull requests has failed checks. Mergify will split this batch to understand which one is responsible for the failure. 🕵️"
```suggestion
                    if self.has_previous_car_status_succeed():
                        headline = "🕵️  This combination of pull requests has failed checks. Mergify will split this batch to understand which pull request is responsible for the failure. 🕵️"
                     else:
                        headline = "🕵️  This combination of pull requests has failed checks. Mergify is waiting for other pull requests ahead in the queue to understand which one is responsible for the failure. 🕵️"
```

2021-08-17 08:50 UTC, jd commented on mergify_engine/queue/merge_train.py
> +        # TODO(sileht): Add a section about failure histories
```suggestion
        # TODO(sileht): Add a section about failure history
```

2021-08-17 08:50 UTC, jd commented on mergify_engine/tests/functional/actions/test_queue.py
> +
Could we add a functional scenario for failure with a split?
That'd be really great to cover it here too.

2021-08-19 09:08 UTC, jd requested changes

2021-08-19 09:08 UTC, jd commented on mergify_engine/utils.py
> +T = typing.TypeVar("T")
```suggestion
_T = typing.TypeVar("_T")
```

2021-08-19 13:52 UTC, jd submitted a review, later dismissed
Missed my comments I think.

2021-08-19 14:23 UTC, jd requested changes
😢

2021-08-19 14:28 UTC, sileht commented on mergify_engine/queue/merge_train.py
> +        # TODO(sileht): Add a section about failure history
yes

2021-08-19 15:13 UTC, jd approved these changes

2021-08-19 15:22 UTC, merged