feat(conditions): add linear-history
Mergifyio/mergify-engine pull request #3142
Opened 2021-09-10 15:13 UTC by sileht

Branch protection allows to block merge if the pull request history is
not linear.

This new conditions allow to do the same thing.

Change-Id: I0d5805d6c17f9d162a16be98fe4025095f27637f

2021-09-10 15:23 UTC, jd submitted a review, later dismissed
doc + release note

2021-09-13 07:41 UTC, jd requested changes

2021-09-13 07:41 UTC, jd commented on docs/source/conditions.rst
> +     - list of string
really?

2021-09-13 08:31 UTC, sileht commented on docs/source/conditions.rst
> +     - list of string
The god of the copy/paste has talked!

2021-09-13 09:52 UTC, jd approved these changes

2021-09-13 09:58 UTC, merged