chore(action_reunner): rewrote comment
Mergifyio/mergify-engine pull request #3152
Opened 2021-09-13 13:14 UTC by sileht

Change-Id: Ib402f16cf54866141017f8c874d387d539ce4b63

2021-09-13 13:35 UTC, jd requested changes
typo in commit title

2021-09-13 13:35 UTC, jd requested changes

2021-09-13 13:35 UTC, jd commented on mergify_engine/engine/actions_runner.py
> +    # somehow
```suggestion
    # NOTE(sileht): fallback on posted check-run in case we lose the Summary
    # somehow
```

2021-09-13 15:00 UTC, jd submitted a review, later dismissed
still a typo in commit title plz fix

2021-09-13 15:03 UTC, sileht commented
> still a typo in commit title plz fix

lol I removed the wrong letter...

2021-09-13 18:57 UTC, jd approved these changes

2021-09-14 08:32 UTC, jd commented
@mergifyio refresh

2021-09-14 08:37 UTC, merged