feat(queue): add more details in case of train reset
Mergifyio/mergify-engine pull request #3154
Opened 2021-09-13 14:38 UTC by sileht

Fixes MRGFY-547

Change-Id: I656dad5a333bf2b4c7f5db52e9af0f65c6ad5341

2021-09-13 15:53 UTC, jd requested changes

2021-09-13 15:53 UTC, jd commented on mergify_engine/queue/merge_train.py
> +        return f"the draft pull request {self.draft_pull_request_number}has been manually updated"
```suggestion
        return f"the draft pull request #{self.draft_pull_request_number} has been manually updated"
```

2021-09-13 15:53 UTC, jd commented on mergify_engine/queue/merge_train.py
> +        return f"the updated pull request #{self.updated_pull_request_number} has been manually updated"
not really clear

2021-09-13 15:53 UTC, jd commented on mergify_engine/engine/queue_runner.py
> +                "body": f"This pull request has unexpected changes, {unexpected_changes}. The whole train will be reset."
```suggestion
                "body": f"This pull request has unexpected changes: {unexpected_changes}. The whole train will be reset."
```

2021-09-13 15:53 UTC, jd commented on mergify_engine/queue/merge_train.py
> +        return f"the base branch head has moved manually to {self.base_sha}"
```suggestion
        return f"an external action moved the branch head {self.base_sha}"
```
Not a fan of this, but I think it sounds better as it really indicates something which is not Mergify did something wrong.
Better idea?

2021-09-13 15:53 UTC, jd commented on mergify_engine/queue/merge_train.py
> +                    headline = f"✨ Unexpected queue change, {unexpected_change}. The pull request {self._get_user_refs()} will be re-embarked soon. ✨"
```suggestion
                    headline = f"✨ Unexpected queue change: {unexpected_change}. The pull request {self._get_user_refs()} will be re-embarked soon. ✨"
```

2021-09-13 15:53 UTC, jd commented on mergify_engine/queue/merge_train.py
> +                f"✨ Unexpected queue change, {unexpected_change}. ✨\n\n"
```suggestion
                f"✨ Unexpected queue change: {unexpected_change}. ✨\n\n"
```

2021-09-13 15:53 UTC, jd commented on mergify_engine/queue/merge_train.py
> +            0, reason=f"Unexpected queue change, {unexpected_change}."
```suggestion
            0, reason=f"Unexpected queue change: {unexpected_change}."
```

2021-09-13 18:44 UTC, sileht commented
@Mergifyio squash first-commit

2021-09-13 18:58 UTC, jd approved these changes

2021-09-14 08:32 UTC, jd commented
@mergifyio refresh

2021-09-14 08:38 UTC, merged