feat(application): add support for account scope
Mergifyio/mergify-engine pull request #3566
Opened 2021-11-05 23:06 UTC by sileht

Fixes MRGFY-648

2021-11-06 14:05 UTC, jd requested changes

2021-11-06 14:47 UTC, sileht commented on mergify_engine/dashboard/application.py
> +                # TODO(sileht): Backward compat, delete me
I already created api key for testing :p

2021-11-06 14:47 UTC, sileht commented
@mergifyio squash

2021-11-08 08:31 UTC, jd approved these changes

2021-11-08 08:38 UTC, merged