fix(queue): use hash to store trains
Mergifyio/mergify-engine pull request #3605
Opened 2021-11-16 20:59 UTC by sileht

Instead of having one key per trains, this change use a hash per
organization and then one key per repo_id/ref.

Since we use iter_trains() more often than before this should load train
faster that before.

Also compared to SCAN, HSCAN also load values, so we also remove one
round-trip to retrieve the data.

2021-11-16 21:01 UTC, sileht commented
TODO:
[ ] write basic unit test for the migration script. 
[X] get a redis dump to measure the downtime migration
[ ] test the migration on the dump

2021-11-16 21:05 UTC, jd requested changes
Release note? We need to handle upgrades and probably us a major version bump when releasing.

2021-11-17 08:23 UTC, sileht commented
I test the migration on a database dump and it was instant locally.

2021-11-17 09:05 UTC, jd approved these changes

2021-11-17 09:12 UTC, merged