WIP feat(queue): add batch_timeout
Mergifyio/mergify-engine pull request #3852
Opened 2021-12-29 15:07 UTC by sileht

Change-Id: I58166215b417043096baea446366553ab497d255

2021-12-29 21:25 UTC, jd submitted a review, later dismissed

2021-12-29 21:25 UTC, jd commented on mergify_engine/rules/__init__.py
> +def BatchTimeout(v: str) -> datetime.timedelta:
```suggestion
def PositiveInterval(v: str) -> datetime.timedelta:
```

2021-12-30 09:09 UTC, sileht commented on docs/source/actions/queue.rst
> +     - 0 s
I didn't want to change the default yet. I prefer finish it with 0 s and then do another PR changing it to 30 s and record all queue tests.

2021-12-31 16:26 UTC, sileht commented
@mregifyio refresh

2022-01-03 13:28 UTC, jd requested changes

2022-01-03 13:28 UTC, jd commented on mergify_engine/queue/merge_train.py
> +                enought_to_batch = (
```suggestion
                enough_to_batch = (
```

2022-01-03 13:28 UTC, jd commented on mergify_engine/queue/merge_train.py
> +                wait_enought_time_to_batch = (
```suggestion
                wait_enough_time_to_batch = (
```

2022-01-03 13:28 UTC, jd commented on mergify_engine/queue/merge_train.py
> +                if not enought_to_batch and not wait_enought_time_to_batch:
```suggestion
                if not enough_to_batch and not wait_enough_time_to_batch:
```

2022-01-05 10:47 UTC, jd approved these changes

2022-01-05 10:55 UTC, merged