chore(api): drop legacy queue api
Mergifyio/mergify-engine pull request #4006
Opened 2022-01-31 08:46 UTC by sileht

Fixes MRGFY-764

Change-Id: I4a482edaff7c871ae8c071cd572a8351729a2012

2022-01-31 13:33 UTC, jd requested changes
changelog?

2022-01-31 15:27 UTC, sileht commented
> changelog?

This API has never been public.

2022-01-31 15:27 UTC, sileht commented
@mergifyio rebase

2022-02-01 10:59 UTC, jd approved these changes

2022-02-01 11:09 UTC, merged