feat(attributes): new repo name attributes (short and full)
Mergifyio/mergify-engine pull request #4072
Opened 2022-02-11 19:22 UTC by ErwanSimonetti

Adding new attributes `repository-name-short` and `repository-name-full`

Fixes MRGFY-905

2022-02-11 19:23 UTC, ErwanSimonetti commented
I'm just missing the release-note because I can't find the exact `reno` command i'm supposed to use

2022-02-12 23:05 UTC, jd requested changes
Name update plz 😁

2022-02-16 08:44 UTC, sileht requested changes
Everything looks good to me. Just a couple of lines I think we can remove.

2022-02-16 08:44 UTC, sileht commented on mergify_engine/context.py
> +    @property
We don't need these new properties, they don't add much value.

2022-02-16 08:44 UTC, sileht commented on mergify_engine/context.py
> +            return self.repo_name
You can directly use `self.repository.repo["name"]`

2022-02-16 10:54 UTC, jd requested changes

2022-02-16 10:54 UTC, jd commented on mergify_engine/context.py
> +
```suggestion
```

2022-02-16 10:54 UTC, jd commented on mergify_engine/context.py
> +            return self.repo_name
```suggestion
            return self.repository.repo["name"]
```

2022-02-16 10:54 UTC, jd commented on mergify_engine/context.py
> +            return self.repo_full_name
```suggestion
            return self.repository.repo["full_name"]
```

2022-02-16 10:54 UTC, jd approved these changes

2022-02-16 11:07 UTC, merged