fix(queue): add message when branch protection is misconfigured
Mergifyio/mergify-engine pull request #4752
Opened 2022-05-22 07:59 UTC by sileht

batch_size and speculative_checks requires branch protection strict mode
to be disabled.

2022-05-22 12:13 UTC, jd reviewed
Can we add a test? 😁

2022-05-23 07:03 UTC, sileht commented
> Can we add a test? 😁

mypy should have catches that..., but it's not implemented yet: https://github.com/python/mypy/issues/12094

2022-05-23 08:50 UTC, Syffe commented on mergify_engine/actions/queue.py
> +                    "batch_size > 1 is not compatible with branch protection a setting",
```suggestion
                    "batch_size > 1 is not compatible with branch protection setting",
```

2022-05-23 08:50 UTC, Syffe commented on mergify_engine/actions/queue.py
> +                    "speculative_checks > 1 is not compatible with branch protection a setting",
```suggestion
                    "speculative_checks > 1 is not compatible with branch protection setting",
```

2022-05-23 16:13 UTC, jd requested changes

2022-05-23 16:13 UTC, jd commented on docs/source/actions/queue.rst
> +   disabled. If you require a linear history, just set the queue option ``merge: rebase``.
```suggestion
   With batch mode, pull requests are tested against the base branch
   within another temporary pull request. This requires the branch protection
   settings ``Require branches to be up to date before merging`` to be
   disabled. If you require a linear history, just set the queue option ``merge: rebase``.
```

2022-05-23 16:14 UTC, jd commented
@mergifyio squash

2022-05-23 16:14 UTC, jd approved these changes

2022-05-24 07:01 UTC, merged